apiVersion: v2
name: helm-file-get-wrapper
description: A Helm chart for Kubernetes
version: 0.2.0
dependencies:
  - name: helm-file-get
    repository: https://jkroepke.github.io/CVE-2022-24348-2
    version: 0.2.0
